# -*- coding: utf-8 -*-
{
	'name': "PS Cloud 合并报表",
	'summary': """PS Cloud 合并报表""",
	'description': """
	""",
	'author': "www.mypscloud.com",
	'website': "https://www.mypscloud.com",

	'category': 'Accounting &amp; Finance',
	'version': '11.0.1.0',

	'depends': ['base', 'mail', 'account', 'fleet', 'account_accountant', 'account_asset'],

	'data': [
		'views/core_value.xml',
        'views/account_account.xml',
        'views/res_partner.xml',
		'views/assets.xml',
		'security/combined_statements_security.xml',
		'security/ir.model.access.csv',
		'data/data.xml',
		'views/base.xml',
		'views/combined_statements_organization.xml',
		'views/combined_statements_subject.xml',
		'views/combined_statements_equity_investment.xml',
		# 'views/combined_statements_classify.xml',
		'views/combined_statements_version.xml',
		'views/combined_statements_elimination_entry.xml',
		# 'views/combined_statements_net_profit.xml',
		'views/combined_statements_fair_value_difference.xml',
		'views/combined_statements_inside_familiar_deal.xml',
		'views/combined_statements_inside_cash_detail.xml',
		'views/combined_statements_inside_inventory_deal.xml',
		'views/combined_statements_inside_asset_deal.xml',
		'views/combined_statements_inside_credit_debt.xml',
		'views/combined_statements_respective_statements.xml',
		'views/combined_statements_merged_subject_contrast.xml',
		'views/combined_statements_equity_contrast.xml',
		'views/combined_statements_merge_manuscript_init.xml',
		'views/combined_statements_journaling_template_view.xml',
		'views/combined_statements_formulas.xml',
		'views/combined_statements_working_papers.xml',
		'views/combined_statements_merge_statements.xml',
		'views/combined_statements_adjust_working_papers.xml',
		'wizard/working_papers_wizard.xml',
		'wizard/merge_statements_wizard.xml',
		'wizard/adjust_working_papers_wizard.xml',
		'wizard/adjust_statements_wizard.xml',
		'wizard/respective_statements_project_wizard.xml',
		'wizard/merge_elimination_entry_builder_wizard.xml',
		'wizard/dialog_info_wizard.xml',
		'views/res_users_inherit.xml',
	],
	'qweb': ['static/xml/*.xml'],
	'installable': True,
	'auto_install': False,
	'application': True,
	'post_init_hook': 'post_init_hook'
}
