# -*- coding: utf-8 -*-
{
    'name': "PS Cloud Production Data（生产数据）",
    'version': '12.0.1.0',
    'summary': "PS Cloud Production Data（PS Cloud生产数据）",
    'author': "www.mypscloud.com",
    'website': 'https://www.mypscloud.com/',
    'category': 'Manufacturing',
    'license': 'OEEL-1',
    'depends': ['mrp', 'odtree'],
    'data': [
        'security/ps_production_data.xml',
        'security/ir.model.access.csv',
        'views/ps_production_data_menuitem.xml',
        'views/ps_production_data_config.xml',
        'views/ps_calendar_resource.xml',
        'data/ps_production_data_data.xml',
        'wizard/ps_resource_calendar_wizard.xml',
        'reports/mrp_report_views_main.xml',
        'reports/mrp_report_materials_forward_query.xml',
        'views/mrp_materials_forward_query_templates.xml',
        'views/ps_mrp_workcenter.xml',
        'views/ps_mrp_routing.xml',
        'views/ps_mrp_routing_query.xml',
        'views/ps_mrp_query_return.xml',
        'views/ps_mrp_bom.xml'
    ],
    'js': ["static/src/js/*.js"],
    'qweb': ['static/src/xml/mrp_report_materials_forward_query_search.xml'],
    'css': ["static/src/scss/*.scss"],
    'installable': True,
    'application': True,
    'auto_install': False,
}