# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': '财务会计',
    'version': '12.0.1.0',
    'summary': 'PS Cloud 财务会计',
    'author': "www.mypscloud.com",
    'website': 'https://www.mypscloud.com/',
    'category': 'Accounting',
    'license': 'OEEL-1',
    'excludes': ['account_china','account_statement','statement_base','account_china_center','stock_account_china_center','inspur_print','account_china_reports','account_cashier','account_cashier_reports','account_account_china','account_china_asset','remove_actions','web_analytics'],
    'depends': ['account', 'account_reports','rowno_in_tree','ps_print_designer','ps_spreadjs'],
    'data': [
        'security/ir.model.access.csv',
        'views/account_china_report_template.xml',
        'views/ps_account_menuitem.xml',
        'views/account_china_reports_menu.xml',
        'views/search_template_view.xml',
        'views/account.xml',
        'views/account_journal.xml',
        'views/account_view.xml',
        'views/account_view_ex.xml',
        'views/ps_account_account.xml',
        'views/ps_account_query_report.xml',
        'data/ps_account_data.xml',
        'security/ps_account_security.xml',
        'views/ps_account_config.xml',
        'views/ps_account_account_base.xml',
        'views/ps_account_month_end.xml',
        'views/ps_account_period.xml',
        'wizard/ps_check_post_account_move.xml',
        'wizard/setup_wizards_view.xml',
        'wizard/parameters_setting.xml',
        # 'views/web_planner_data.xml',
        'data/print_account_move.xml',
        'data/ps_account_payment_use_data.xml',
        'views/ps_account_statement_menu.xml',
        'data/ps_statement_sheet_rows_data.xml',
        'data/ps_statement_sheet_columns_data.xml',
        'data/ps_statement_sheet_cells_data.xml',
        'data/ps_statement_formulas_data.xml',
        'data/ps_statement_formulas_params_data.xml',
        'data/ps_statement_statements_data.xml',
        'data/ps_statement_formulas_sequence_data.xml',
        'data/ps_statement_system_variables_data.xml',
        'data/ps_statement_functions_data.xml',
        'data/ps_statement_function_params_data.xml',
        'views/ps_account_payment_add_cash_flow_item.xml',
        'views/account_dashboard_setup_bar.xml',
        'views/ps_account_payment_use.xml',
        'views/ps_account_adjust_exchange_rate.xml',
        'views/ps_account_carry_over.xml',

        # 'wizard/action_account_template.xml',
        # 'wizard/action_account_select.xml',

    ],
    'demo': ['data/ps_account_demo.xml'],
    'qweb': [
        "static/src/xml/button.xml",
        "static/src/xml/month.xml",
        "static/src/xml/loss_account.xml",
        "static/src/xml/dashboard.xml"
    ],
    'js': ['static/src/js/*.js'],
    'css': ['static/src/css/*.css'],
    'installable': True,
    'application': True,
    'auto_install': False,
    # 'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
}