# -*- coding: utf-8 -*-
{
    'name': "PS Cloud WMS 会计",
    'version': '1.0',
    'summary': "PS Cloud 库存单据生成凭证",
    'sequence': 10,
    'author': "www.mypscloud.com",
    'website': 'https://www.mypscloud.com/',
    'description': "中国财务会计库存凭证桥接模块",
    'category': 'Hidden',
    'depends': ['ps_account_center', 'stock','account_reports'],
    'license': 'OEEL-1',
    'data': [
        'security/ir.model.access.csv',
        'data/stock_data.xml',
        'views/ps_stock_picking_move.xml',
        'views/views.xml',
        'views/product_view.xml',
        'views/cancel_move.xml',
        'views/search_template_view.xml',
        'views/query_move.xml',
        'views/outbound_cost_calculation_template.xml',
        'wizard/ps_stock_create_account_move_wizard.xml',
        'wizard/ps_stock_cancel_account_move_wizard.xml',
        'views/product_alter_cost_position_view.xml',
        'views/ps_purchase_stock_verification.xml',
        'wizard/ps_check_outbound_cost_calculation_wizard.xml',
        'views/ps_stock_cost_maintenance.xml',
        'wizard/ps_stock_cost_maintenance_wizard.xml',
        'views/inventory_details_template.xml',
        'views/inventory_summary_template.xml',
        'views/ps_account_center_reports_menu.xml',
        'views/report_financial.xml',
    ],
    'qweb': ["static/src/xml/*.xml"],
    'js': ["static/src/js/*.js"],
    'css': ["static/src/css/*.css"],
    'installable': True,
    'application': False,
    'auto_install': True,
}