# -*- coding: utf-8 -*-
{
    'name': "PS Cloud 信用管理",
    'version': '12.0.1.0',
    'summary': "credit limit management and control",
    'description': """""",
    'author': "www.mypscloud.com",
    'website': 'https://www.mypscloud.com/',
    'category': 'Accounting & Finance',
    'depends': ['sale', 'account', 'stock', 'ps_stock', 'account_reports', 'ps_sale'],
    'license': 'LGPL-3',
    'data': [
        'data/credit_level.xml',
        'data/ps_credit_management_demo.xml',
        'security/ps_credit_management_security.xml',
        'security/ir.model.access.csv',
        'views/ps_credit_level_view.xml',
        'views/ps_credit_profile_view.xml',
        'views/ps_credit_usage_view.xml',
        'views/ps_credit_check_scheme_views.xml',
        'views/ps_credit_management_menu.xml',
        'views/ps_partner_credit_profile_view.xml',
        'wizard/ps_credit_confirm_views.xml',
        'views/ps_account_invoice_view.xml',
    ],
    'demo': [
        'demo/credit_profile_demo.xml',
        'demo/credit_check_scheme_demo.xml',
        'demo/credit_check_confirm.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
