# -*- coding: utf-8 -*-
{
    'name': 'PS Cloud 报表基础',
    'version' : '12.0.1.0',
    'summary': 'PS Cloud 财务报表基础',
    'author': 'www.mypscloud.com',
    'website': 'https://www.mypscloud.com/',
    'category': 'Tools',
    'license': 'OEEL-1',
    'depends': ['web'],
    'data': [
        'views/assets.xml',
        'views/views.xml',
        'views/tree_view_asset.xml',
        'security/ir.model.access.csv',
        # 'views/res_config_settings_views.xml',
        'wizard/ps_statement_statements.xml',
    ],
    'qweb': ["static/src/xml/*.xml"],
    'js': ["static/src/js/*.js"],
    'css': ["static/src/css/*.css"],
    'installable': True,
    'application': False,
    'auto_install': False,
}