# -*- coding: utf-8 -*-

from odoo import models, api, fields, _
from odoo.exceptions import UserError


class ResConfigSettings(models.TransientModel):
    _inherit = 'res.config.settings'

    ps_profit_loss_same_user_approval = fields.Boolean(string=_("Direct verification of voucher generated by profit and loss transfer"))

    def save_profit_loss_parameter(self):
        self.set_values()

    @api.model
    def get_view_id(self):
        view_id = self.env.ref('ps_account.setup_profit_loss_parameters_form').id
        return view_id



